import{describe,expect,it}from'vitest'
import{CONFIG_NUMERIC_RANGES,CONFIG_VERSION,defaultConfig,LEGACY_V3_CONFIG_KEYS,MAX_FOOD,MAX_HISTORY_POINTS,MAX_POPULATION,sanitizeConfig,validateExactConfig}from'./config'
import{configFromSearch,decodeExperiment,encodeExperiment,exportExperiment,importExperiment,LEGACY_STORAGE_KEY,LEGACY_V2_STORAGE_KEY,loadInitialConfig,MAX_EXPERIMENT_QUERY,MAX_EXPERIMENT_TEXT,persistExperiment,STORAGE_KEY}from'./share'
import{createWorld,finishGeneration,runGeneration}from'./engine'

describe('versioned configuration',()=>{
  it('uses advanced v4 modes and keeps every numeric default inside its declared bounds',()=>{expect(defaultConfig).toMatchObject({ecologyMode:'energy-regrowth',perceptionMode:'realistic',predationMode:'contest',obstacleOcclusion:true});for(const [key,[min,max]]of Object.entries(CONFIG_NUMERIC_RANGES)){const value=defaultConfig[key as keyof typeof defaultConfig]as number;expect(value,`${key} default`).toBeGreaterThanOrEqual(min);expect(value,`${key} default`).toBeLessThanOrEqual(max)}})
  it('sanitizes missing, unknown, non-finite, out-of-range, and invalid enum fields',()=>{const c=sanitizeConfig({seed:Infinity,initialPopulation:9999,foodPerDay:-4,startSpeed:NaN,maxAge:999,fieldOfView:0,obstacleOcclusion:false,ecologyMode:'unknown',unknown:true});expect(c.seed).toBe(defaultConfig.seed);expect(c.initialPopulation).toBe(MAX_POPULATION);expect(c.foodPerDay).toBe(0);expect(c.startSpeed).toBe(defaultConfig.startSpeed);expect(c.maxAge).toBe(200);expect(c.fieldOfView).toBe(15);expect(c.obstacleOcclusion).toBe(false);expect(c.ecologyMode).toBe(defaultConfig.ecologyMode);expect(Object.keys(c)).not.toContain('unknown')})
  it('strictly validates exact current-version configs without repairing them',()=>{expect(validateExactConfig(defaultConfig)).toEqual(defaultConfig);for(const invalid of[{...defaultConfig,seed:Infinity},{...defaultConfig,initialPopulation:4.5},{...defaultConfig,foodRegrowthRate:2},{...defaultConfig,ecologyMode:'unknown'},{...defaultConfig,obstacleOcclusion:1},Object.fromEntries(Object.entries(defaultConfig).filter(([key])=>key!=='seed')),{...defaultConfig,unknown:true}])expect(validateExactConfig(invalid)).toBeNull()})
  it('round-trips the full configuration through URL and JSON',()=>{const c=sanitizeConfig({...defaultConfig,seed:7654,startAggression:.13,foodTrend:.03});expect(decodeExperiment(encodeExperiment(c))).toEqual(c);expect(importExperiment(exportExperiment(c))).toEqual(c);expect(configFromSearch(`?experiment=${encodeExperiment(c)}`)).toEqual(c)})
  it('rejects future, corrupt, unrecognized, and oversized formats and migrates older envelopes',()=>{expect(importExperiment('{bad')).toBeNull();expect(importExperiment('{}')).toBeNull();expect(importExperiment('[]')).toBeNull();expect(importExperiment('3')).toBeNull();expect(importExperiment(JSON.stringify({mystery:true}))).toBeNull();expect(importExperiment(JSON.stringify({version:CONFIG_VERSION+1,config:defaultConfig}))).toBeNull();expect(importExperiment('x'.repeat(MAX_EXPERIMENT_TEXT+1))).toBeNull();expect(decodeExperiment('x'.repeat(MAX_EXPERIMENT_QUERY+1))).toBeNull();expect(importExperiment(JSON.stringify({version:1,settings:{seed:44,foodPerDay:9}}))).toMatchObject({seed:44,foodPerDay:9,...{ecologyMode:'classic',perceptionMode:'perfect',predationMode:'threshold'}});expect(importExperiment(JSON.stringify({seed:45,initialPopulation:4,foodPerDay:8}))).toMatchObject({seed:45,initialPopulation:4,foodPerDay:8,ecologyMode:'classic'});const v3=Object.fromEntries(LEGACY_V3_CONFIG_KEYS.map(key=>[key,defaultConfig[key]]));expect(importExperiment(JSON.stringify({version:3,config:v3}))).toMatchObject({ecologyMode:'classic',perceptionMode:'perfect',predationMode:'threshold',founderPhysicalVariation:defaultConfig.founderPhysicalVariation})})
  it('rejects malformed v4 envelopes while keeping legacy migrations permissive',()=>{for(const envelope of[{version:CONFIG_VERSION},{version:CONFIG_VERSION,config:defaultConfig,extra:true}])expect(importExperiment(JSON.stringify(envelope))).toBeNull();for(const config of[{},Object.fromEntries(Object.entries(defaultConfig).filter(([key])=>key!=='seed')),{...defaultConfig,unknown:1},{...defaultConfig,initialPopulation:4.2},{...defaultConfig,attackCost:101},{...defaultConfig,predationMode:'unknown'}])expect(importExperiment(JSON.stringify({version:CONFIG_VERSION,config}))).toBeNull();expect(importExperiment(JSON.stringify({version:3,config:{seed:5,foodPerDay:-20,unknown:true},extra:true}))).toMatchObject({seed:5,foodPerDay:0,ecologyMode:'classic'});expect(importExperiment(JSON.stringify({seed:6,initialPopulation:4,foodPerDay:8,extra:true}))).toMatchObject({seed:6,ecologyMode:'classic'})})
  it('uses URL then v4/v3/v2 storage then defaults and survives denied storage',()=>{const url=sanitizeConfig({...defaultConfig,seed:11}),stored=sanitizeConfig({...defaultConfig,seed:22}),storage={getItem:()=>exportExperiment(stored),setItem:()=>{}};expect(loadInitialConfig(`?experiment=${encodeExperiment(url)}`,storage).seed).toBe(11);expect(loadInitialConfig('',storage).seed).toBe(22);const legacyStorage={getItem:(key:string)=>key===LEGACY_STORAGE_KEY?JSON.stringify({version:3,config:{seed:33,initialPopulation:4,foodPerDay:8}}):key===LEGACY_V2_STORAGE_KEY?JSON.stringify({version:2,config:{seed:44,initialPopulation:4,foodPerDay:8}}):null,setItem:()=>{}};expect(loadInitialConfig('',legacyStorage)).toMatchObject({seed:33,ecologyMode:'classic'});const denied={getItem(){throw Error('denied')},setItem(){throw Error('denied')}};expect(loadInitialConfig('',denied)).toEqual(defaultConfig);expect(()=>persistExperiment(url,denied)).not.toThrow();expect(STORAGE_KEY).toContain('v4')})
  it('shared experiments reproduce deterministic first generations',()=>{const c=sanitizeConfig({...defaultConfig,seed:919,initialPopulation:12,foodPerDay:14}),decoded=decodeExperiment(encodeExperiment(c))!;const a=createWorld(c),b=createWorld(decoded);runGeneration(a);runGeneration(b);expect(a).toEqual(b)})
  it('preserves every saturated survivor before admitting births and reconciles reports',()=>{const w=createWorld({...defaultConfig,initialPopulation:MAX_POPULATION,mutationRate:1});const traits=w.creatures.map((c,i)=>(c.speed=.3+i*.01,c.speed));for(const c of w.creatures){c.alive=true;c.home=true;c.food=2}finishGeneration(w);expect(w.creatures).toHaveLength(MAX_POPULATION);expect(w.creatures.map(c=>c.speed)).toEqual(traits);expect(w.lastReport).toMatchObject({survived:MAX_POPULATION,born:0})})
  it('caps seasonal food and retained history',()=>{const w=createWorld({...defaultConfig,initialPopulation:2,foodPerDay:120,seasonAmplitude:.9,foodTrend:.1});w.history=Array.from({length:MAX_HISTORY_POINTS},(_,generation)=>({...w.history[0],generation}));for(let i=0;i<20;i++){w.environment.foodBudget=MAX_FOOD*2;for(const c of w.creatures){c.home=true;c.food=1}finishGeneration(w)}expect(w.food.length).toBeLessThanOrEqual(MAX_FOOD);expect(w.history).toHaveLength(MAX_HISTORY_POINTS);expect(w.history.at(-1)?.generation).toBe(w.generation-1)})
})
