import{describe,expect,it}from'vitest'
import{CONFIG_VERSION,defaultConfig,MAX_FOOD,MAX_HISTORY_POINTS,MAX_POPULATION,sanitizeConfig}from'./config'
import{configFromSearch,decodeExperiment,encodeExperiment,exportExperiment,importExperiment,loadInitialConfig,MAX_EXPERIMENT_QUERY,MAX_EXPERIMENT_TEXT,persistExperiment,STORAGE_KEY}from'./share'
import{createWorld,finishGeneration,runGeneration}from'./engine'

describe('versioned configuration',()=>{
  it('sanitizes missing, unknown, non-finite, and out-of-range fields',()=>{const c=sanitizeConfig({seed:Infinity,initialPopulation:9999,foodPerDay:-4,startSpeed:NaN,unknown:true});expect(c.seed).toBe(defaultConfig.seed);expect(c.initialPopulation).toBe(MAX_POPULATION);expect(c.foodPerDay).toBe(0);expect(c.startSpeed).toBe(defaultConfig.startSpeed);expect(Object.keys(c)).not.toContain('unknown')})
  it('round-trips the full configuration through URL and JSON',()=>{const c=sanitizeConfig({...defaultConfig,seed:7654,startAggression:.13,foodTrend:.03});expect(decodeExperiment(encodeExperiment(c))).toEqual(c);expect(importExperiment(exportExperiment(c))).toEqual(c);expect(configFromSearch(`?experiment=${encodeExperiment(c)}`)).toEqual(c)})
  it('rejects future, corrupt, unrecognized, and oversized formats and migrates older envelopes',()=>{expect(importExperiment('{bad')).toBeNull();expect(importExperiment('{}')).toBeNull();expect(importExperiment('[]')).toBeNull();expect(importExperiment('3')).toBeNull();expect(importExperiment(JSON.stringify({mystery:true}))).toBeNull();expect(importExperiment(JSON.stringify({version:CONFIG_VERSION+1,config:defaultConfig}))).toBeNull();expect(importExperiment('x'.repeat(MAX_EXPERIMENT_TEXT+1))).toBeNull();expect(decodeExperiment('x'.repeat(MAX_EXPERIMENT_QUERY+1))).toBeNull();expect(importExperiment(JSON.stringify({version:1,settings:{seed:44,foodPerDay:9}}))).toMatchObject({seed:44,foodPerDay:9});expect(importExperiment(JSON.stringify({seed:45,initialPopulation:4,foodPerDay:8}))).toMatchObject({seed:45,initialPopulation:4,foodPerDay:8})})
  it('uses URL then storage then defaults and survives denied storage',()=>{const url=sanitizeConfig({...defaultConfig,seed:11}),stored=sanitizeConfig({...defaultConfig,seed:22}),storage={getItem:()=>exportExperiment(stored),setItem:()=>{}};expect(loadInitialConfig(`?experiment=${encodeExperiment(url)}`,storage).seed).toBe(11);expect(loadInitialConfig('',storage).seed).toBe(22);const denied={getItem(){throw Error('denied')},setItem(){throw Error('denied')}};expect(loadInitialConfig('',denied)).toEqual(defaultConfig);expect(()=>persistExperiment(url,denied)).not.toThrow();expect(STORAGE_KEY).toContain('v3')})
  it('shared experiments reproduce deterministic first generations',()=>{const c=sanitizeConfig({...defaultConfig,seed:919,initialPopulation:12,foodPerDay:14}),decoded=decodeExperiment(encodeExperiment(c))!;const a=createWorld(c),b=createWorld(decoded);runGeneration(a);runGeneration(b);expect(a).toEqual(b)})
  it('preserves every saturated survivor before admitting births and reconciles reports',()=>{const w=createWorld({...defaultConfig,initialPopulation:MAX_POPULATION,mutationRate:1});const traits=w.creatures.map((c,i)=>(c.speed=.3+i*.01,c.speed));for(const c of w.creatures){c.alive=true;c.home=true;c.food=2}finishGeneration(w);expect(w.creatures).toHaveLength(MAX_POPULATION);expect(w.creatures.map(c=>c.speed)).toEqual(traits);expect(w.lastReport).toMatchObject({survived:MAX_POPULATION,born:0})})
  it('caps seasonal food and retained history',()=>{const w=createWorld({...defaultConfig,initialPopulation:2,foodPerDay:120,seasonAmplitude:.9,foodTrend:.1});w.history=Array.from({length:MAX_HISTORY_POINTS},(_,generation)=>({...w.history[0],generation}));for(let i=0;i<20;i++){w.environment.foodBudget=MAX_FOOD*2;for(const c of w.creatures){c.home=true;c.food=1}finishGeneration(w)}expect(w.food.length).toBeLessThanOrEqual(MAX_FOOD);expect(w.history).toHaveLength(MAX_HISTORY_POINTS);expect(w.history.at(-1)?.generation).toBe(w.generation-1)})
})
