import{describe,expect,it}from'vitest'
import{createWorld,defaultConfig,finishGeneration,summarizeValues}from'./engine'
import{summarizeDistribution}from'../components/Charts'
import{CONFIG_VERSION}from'./config'
import{CLASSIC_MODES}from'./config'
import{importExperiment}from'./share'

describe('stable biological identity and ledger',()=>{
  it('keeps an adult identity and correct lineage links across five generations',()=>{const w=createWorld({...defaultConfig,...CLASSIC_MODES,seed:77,initialPopulation:1,foodPerDay:0,mutationRate:0,founderPhysicalVariation:0,founderBehaviorVariation:0}),founder=w.creatures[0],individual=founder.individualId,lineage=founder.lineageId;const children:number[]=[]
    for(let generation=1;generation<=5;generation++){const adult=w.creatures.find(c=>c.individualId===individual)!;for(const c of w.creatures){c.alive=true;c.home=true;c.food=c.individualId===individual?2:1}finishGeneration(w);const continued=w.creatures.find(c=>c.individualId===individual)!;expect(continued.lineageId).toBe(lineage);expect(continued.birthGeneration).toBe(1);expect(continued.age).toBe(generation);const child=w.creatures.find(c=>c.birthGeneration===generation+1&&c.parentIndividualId===individual)!;expect(child.lineageId).toBe(lineage);children.push(child.individualId)}expect(new Set(children).size).toBe(5)})
  it('reconciles mutually exclusive end causes and resource mass balance',()=>{const w=createWorld({...defaultConfig,...CLASSIC_MODES,initialPopulation:5,foodPerDay:10,founderPhysicalVariation:0,founderBehaviorVariation:0}),[survivor,hunted,energy,unfed,late]=w.creatures;Object.assign(survivor,{alive:true,home:true,food:1});Object.assign(hunted,{alive:false,deathCause:'hunted'});Object.assign(energy,{alive:false,deathCause:'energy'});Object.assign(unfed,{alive:true,home:false,food:0});Object.assign(late,{alive:true,home:false,food:1});w.dayFoodConsumed=2;w.food=w.food.slice(2);finishGeneration(w);const ledger=w.ledger[0],total=Object.values(ledger.outcomes).reduce((a,b)=>a+b,0);expect(ledger.outcomes).toEqual({survived:1,hunted:1,energy:1,unfed:1,late:1,aged:0});expect(total).toBe(ledger.startPopulation);expect(ledger.foodAtStart).toBe(ledger.foodConsumed+ledger.foodRemaining);expect(ledger.selection.start.speed.mean).not.toBeNull()})
  it('profiles each original outcome cohort without leakage and replays deterministically',()=>{const cfg={...defaultConfig,...CLASSIC_MODES,seed:123,initialPopulation:5,foodPerDay:10,founderPhysicalVariation:0,founderBehaviorVariation:0,mutationRate:0},a=createWorld(cfg),b=structuredClone(a),prepare=(w:typeof a)=>{const [survivor,hunted,energy,unfed,late]=w.creatures;const speeds=[.5,.7,.9,1.1,1.3];w.creatures.forEach((creature,index)=>{creature.speed=speeds[index]});Object.assign(survivor,{alive:true,home:true,food:1});Object.assign(hunted,{alive:false,deathCause:'hunted'});Object.assign(energy,{alive:false,deathCause:'energy'});Object.assign(unfed,{alive:true,home:false,food:0});Object.assign(late,{alive:true,home:false,food:1});w.dayFoodConsumed=2;w.food=w.food.slice(2)};prepare(a);prepare(b);finishGeneration(a);finishGeneration(b);const ledger=a.ledger[0],profiles=ledger.selectionByOutcome;expect(Object.keys(profiles)).toEqual(['survived','hunted','energy','unfed','late','aged']);expect(ledger.outcomes).toEqual({survived:1,hunted:1,energy:1,unfed:1,late:1,aged:0});expect(Object.values(ledger.outcomes).reduce((sum,count)=>sum+count,0)).toBe(ledger.startPopulation);expect(profiles.survived.speed.mean).toBe(.5);expect(profiles.hunted.speed.mean).toBe(.7);expect(profiles.energy.speed.mean).toBe(.9);expect(profiles.unfed.speed.mean).toBe(1.1);expect(profiles.late.speed.mean).toBe(1.3);expect(Object.values(profiles.aged).every(moment=>moment.mean===null&&moment.variance===null&&moment.sd===null)).toBe(true);expect(a.rngState).toBe(b.rngState);expect(a.ledger[0].selectionByOutcome).toEqual(b.ledger[0].selectionByOutcome)})
})

describe('founder standing variation and distributions',()=>{
  it('makes zero variation exactly clonal and seeded variation deterministic and bounded',()=>{const cfg={...defaultConfig,seed:404,initialPopulation:100,founderPhysicalVariation:0,founderBehaviorVariation:0},clonal=createWorld(cfg);expect(clonal.creatures.every(c=>c.speed===cfg.startSpeed&&c.aggression===cfg.startAggression)).toBe(true);const varied={...cfg,founderPhysicalVariation:.2,founderBehaviorVariation:.2},a=createWorld(varied),b=createWorld(varied);expect(a.creatures).toEqual(b.creatures);expect(a.creatures.every(c=>c.speed>=.3&&c.speed<=2.8&&c.sense>=.035&&c.sense<=.6&&c.aggression>=0&&c.aggression<=1)).toBe(true)})
  it('produces robustly greater spread at high than low diversity',()=>{const base={...defaultConfig,seed:905,initialPopulation:120},low=createWorld({...base,founderPhysicalVariation:.01,founderBehaviorVariation:.01}),high=createWorld({...base,founderPhysicalVariation:.25,founderBehaviorVariation:.25});expect(summarizeValues(high.creatures.map(c=>c.speed)).sd!).toBeGreaterThan(summarizeValues(low.creatures.map(c=>c.speed)).sd!*5);expect(summarizeValues(high.creatures.map(c=>c.aggression)).sd!).toBeGreaterThan(summarizeValues(low.creatures.map(c=>c.aggression)).sd!*5)})
  it('calculates fixture quantiles and spread correctly',()=>{expect(summarizeDistribution([1,2,3,4])).toEqual({mean:2.5,median:2.5,q1:1.75,q3:3.25,iqr:1.5,sd:Math.sqrt(1.25)})})
  it('migrates v2 experiments to clonal classic founders to preserve prior runs',()=>{const migrated=importExperiment(JSON.stringify({version:2,config:{...defaultConfig,founderPhysicalVariation:.2,founderBehaviorVariation:.2}}))!;expect(CONFIG_VERSION).toBe(4);expect(migrated).toMatchObject({ecologyMode:'classic',perceptionMode:'perfect',predationMode:'threshold',founderPhysicalVariation:0,founderBehaviorVariation:0})})
})
