import{describe,expect,it}from'vitest'
import{defaultConfig}from'./config'
import{createWorld}from'./engine'
import{keyedRandom}from'./random'
import type{Creature,Food,Obstacle}from'./types'
import{detectionProbability,perceive,reactionWindowFor}from'./perception'

const config=(overrides:Partial<typeof defaultConfig>={})=>({...defaultConfig,perceptionMode:'realistic' as const,fieldOfView:360,detectionFalloff:0,obstacleOcclusion:false,...overrides})
const creature=(id:number,x:number,y:number,overrides:Partial<Creature>={}):Creature=>({id,x,y,homeX:.5,homeY:.5,angle:0,vx:0,vy:0,individualId:id,lineageId:id,parentIndividualId:null,birthGeneration:1,speed:1,size:1,sense:1,aggression:.5,caution:.5,exploration:.5,energy:100,food:0,alive:true,returning:false,home:false,age:0,mode:'exploring',memory:{foodX:null,foodY:null,foodUntil:0,threatX:null,threatY:null,threatUntil:0},targetType:null,targetId:null,targetX:x,targetY:y,commitUntil:0,wanderAngle:0,wanderTurn:0,reactionWindow:-1,attackCooldownUntil:0,deathCause:null,...overrides})
const food=(id:number,x:number,y:number):Food=>({id,x,y,patchId:null,energy:22})

describe('perceive',()=>{
  it('passes perfect-mode inputs through as stable-id-sorted references',()=>{const observer=creature(2,.5,.5),other=creature(1,.7,.5),foods:Food[]=[food(4,.9,.9),food(3,.1,.1)];const result=perceive(observer,[observer,other],foods,[],config({perceptionMode:'perfect'}),1,9,.7);expect(result.creatures).toEqual([other,observer]);expect(result.food).toEqual([...foods].reverse());expect(result.creatures[0]).toBe(other);expect(result.food[0]).toBe(foods[1]);expect(result.diagnostics).toMatchObject({mode:'perfect',creatures:{total:1,detected:1},food:{total:2,detected:2}})})
  it('rejects targets by range, field of view, and obstacle line of sight',()=>{const observer=creature(1,.5,.5,{sense:.3,angle:0});const ahead=creature(2,.7,.5),behind=creature(3,.4,.5),far=creature(4,.9,.5);const foods:Food[]=[food(10,.7,.5)];const obstacle:Obstacle={id:1,x:.6,y:.5,radius:.03};const result=perceive(observer,[far,behind,ahead,observer],foods,[obstacle],config({fieldOfView:90,obstacleOcclusion:true}),1,0,0);expect(result.creatures.map(c=>c.id)).toEqual([1]);expect(result.food).toEqual([]);expect(result.diagnostics.creatures).toMatchObject({total:3,detected:0,range:1,fov:1,occlusion:1,detection:0});expect(result.diagnostics.food.occlusion).toBe(1)})
  it('uses a monotonic distance detection probability',()=>{const values=[0,.25,.5,.75,1].map(d=>detectionProbability(d,1,.8));expect(values).toEqual([...values].sort((a,b)=>b-a));expect(values[0]).toBe(1);expect(values.at(-1)).toBeCloseTo(.2);expect(detectionProbability(1.01,1,.8)).toBe(0);expect(detectionProbability(1,0,.5)).toBe(0)})
  it('holds keyed draws inside reaction windows and changes keys across windows and generations',()=>{expect(reactionWindowFor(.2,99,.19)).toBe(0);expect(reactionWindowFor(.2,99,.2)).toBe(1);expect(reactionWindowFor(0,7,.2)).toBe(7);const observer=creature(1,0,0),target=creature(2,.8,0),seed=37,cfg=config({seed,detectionFalloff:.8,reactionTime:.2});const first=perceive(observer,[observer,target],[],[],cfg,1,1,.01),same=perceive(observer,[observer,target],[],[],cfg,1,19,.19),next=perceive(observer,[observer,target],[],[],cfg,1,20,.2);expect(first.diagnostics.reactionWindow).toBe(same.diagnostics.reactionWindow);expect(first.creatures.map(c=>c.id)).toEqual(same.creatures.map(c=>c.id));expect(next.diagnostics.reactionWindow).toBe(1);expect(keyedRandom(seed,'perception-creature',1,1,2,0)).not.toBe(keyedRandom(seed,'perception-creature',1,1,2,1));expect(keyedRandom(seed,'perception-creature',1,1,2,0)).not.toBe(keyedRandom(seed,'perception-creature',2,1,2,0))})
  it('is deterministic and invariant to creature, food, and obstacle permutations',()=>{const observer=creature(4,.5,.5,{sense:.6,angle:.2}),others=[creature(3,.2,.5),creature(8,.8,.55),observer,creature(6,.55,.8)],foods:Food[]=[food(20,.75,.5),food(10,.4,.4)],obstacles:Obstacle[]=[{id:2,x:.6,y:.7,radius:.03},{id:1,x:.35,y:.5,radius:.04}];const cfg=config({seed:487,detectionFalloff:.73,fieldOfView:250,obstacleOcclusion:true,reactionTime:.3});const forward=perceive(observer,others,foods,obstacles,cfg,2,12,.43),reverse=perceive(observer,[...others].reverse(),[...foods].reverse(),[...obstacles].reverse(),cfg,2,12,.43);expect(reverse).toEqual(forward);expect(perceive(observer,others,foods,obstacles,cfg,2,12,.43)).toEqual(forward)})
  it('does not mutate world RNG state or source arrays',()=>{const world=createWorld(config({seed:1337})),observer=world.creatures[0],creatures=[...world.creatures].reverse(),food=[...world.food].reverse(),obstacles=[...world.environment.obstacles].reverse(),before={rngState:world.rngState,creatureIds:creatures.map(c=>c.id),foodIds:food.map(f=>f.id),obstacleIds:obstacles.map(o=>o.id)};perceive(observer,creatures,food,obstacles,world.config,world.generation,world.tickIndex,world.dayTime);expect(world.rngState).toBe(before.rngState);expect(creatures.map(c=>c.id)).toEqual(before.creatureIds);expect(food.map(f=>f.id)).toEqual(before.foodIds);expect(obstacles.map(o=>o.id)).toEqual(before.obstacleIds)})
})
